# Generated by Django 4.2.20 on 2025-05-15 23:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cadastros", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120)),
                ("descricao", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ["nome"],
            },
        ),
        migrations.DeleteModel(
            name="Status",
        ),
    ]
