# Generated by Django 5.2 on 2025-08-17 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_itempedido_usuario_pedido_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempedido',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='usuario',
        ),
    ]
